#!/bin/bash
# Formats copied 10 or 11 digit united states numbers nicely
n=$(pbpaste)
n=`echo "$n" | tr -d "+"` #remove + if it's in n.
length=`echo|awk "{print length ("$n")}"`
	if [[ $length = 10 ]]; then
		#10-digit USA format
		printf "(${n:0:3})-${n:3:3}-${n:6}";
	elif [[ $length = 11 ]]; then
		#11-digit USA format
		printf "${n:0:1}-(${n:1:3})-${n:4:3}-${n:7}" | tr -d "+";
	else
		printf "wrong length";
fi
